export const spanish500 = [
  { targetWord: 'gente', translating: 'люди', skyid: null },
  { targetWord: 'persona', translating: 'человек', skyid: null },
  { targetWord: 'hombre', translating: 'мужчина', skyid: null },
  { targetWord: 'marido', translating: 'муж', skyid: null },
  { targetWord: 'mujer', translating: 'женщина, жена', skyid: null },
  { targetWord: 'niño', translating: 'ребенок', skyid: null },
  { targetWord: 'muchacho⁄a', translating: 'мальчик⁄девочка', skyid: null },
  { targetWord: 'amigo', translating: 'друг', skyid: null },
  { targetWord: 'invitado', translating: 'гость', skyid: null },
  { targetWord: 'familia', translating: 'семья', skyid: null },
  { targetWord: 'padres', translating: 'родители', skyid: null },
  { targetWord: 'padre', translating: 'отец', skyid: null },
  { targetWord: 'madre', translating: 'мать', skyid: null },
  { targetWord: 'hijo⁄a', translating: 'сын⁄дочь', skyid: null },
  { targetWord: 'abuelo⁄a', translating: 'дед⁄бабушка', skyid: null },
  {
    targetWord: 'suegro⁄a',
    translating: 'тесть (свекор)⁄теща (свекровь)',
    skyid: null
  },
  { targetWord: 'tío⁄a', translating: 'дядя⁄тетя', skyid: null },
  { targetWord: 'hermano⁄a', translating: 'брат⁄сестра', skyid: null },
  {
    targetWord: 'primo⁄a',
    translating: 'двоюродный брат⁄сестра',
    skyid: null
  },
  { targetWord: 'trabajo', translating: 'работа', skyid: null },
  { targetWord: 'maestro', translating: 'учитель', skyid: null },
  { targetWord: 'conductor', translating: 'водитель', skyid: null },
  { targetWord: 'obrero', translating: 'рабочий', skyid: null },
  { targetWord: 'ingeniero', translating: 'инженер', skyid: null },
  { targetWord: 'doctor', translating: 'врач', skyid: null },
  { targetWord: 'enfermera', translating: 'медсестра', skyid: null },
  { targetWord: 'vendedor', translating: 'продавец', skyid: null },
  { targetWord: 'contador', translating: 'бухгалтер', skyid: null },
  { targetWord: 'pintor', translating: 'художник', skyid: null },
  { targetWord: 'estudiante', translating: 'студент', skyid: null },
  { targetWord: 'país', translating: 'страна', skyid: null },
  { targetWord: 'Rusia', translating: 'Россия', skyid: null },
  { targetWord: 'España', translating: 'Испания', skyid: null },
  { targetWord: 'animal', translating: 'животное', skyid: null },
  { targetWord: 'gato', translating: 'кошка', skyid: null },
  { targetWord: 'perro', translating: 'собака', skyid: null },
  { targetWord: 'pájaro', translating: 'птица', skyid: null },
  { targetWord: 'ciudad', translating: 'город', skyid: null },
  { targetWord: 'escuela', translating: 'школа', skyid: null },
  { targetWord: 'teatro', translating: 'театр', skyid: null },
  { targetWord: 'calle', translating: 'улица', skyid: null },
  { targetWord: 'plaza', translating: 'площадь', skyid: null },
  { targetWord: 'lugar', translating: 'место', skyid: null },
  { targetWord: 'casa', translating: 'дом', skyid: null },
  { targetWord: 'iglesia', translating: 'церковь', skyid: null },
  { targetWord: 'río', translating: 'река', skyid: null },
  { targetWord: 'café', translating: 'кафе, кофе', skyid: null },
  { targetWord: 'hotel', translating: 'гостиница', skyid: null },
  { targetWord: 'jardín', translating: 'сад', skyid: null },
  { targetWord: 'parque', translating: 'парк', skyid: null },
  { targetWord: 'banco', translating: 'банк', skyid: null },
  { targetWord: 'parada', translating: 'остановка', skyid: null },
  { targetWord: 'cine', translating: 'кинотеатр', skyid: null },
  { targetWord: 'puente', translating: 'мост', skyid: null },
  { targetWord: 'intersección', translating: 'перекрёсток', skyid: null },
  { targetWord: 'bosque', translating: 'лес', skyid: null },
  { targetWord: 'hospital', translating: 'больница', skyid: null },
  { targetWord: 'mercado', translating: 'рынок', skyid: null },
  { targetWord: 'policía', translating: 'полиция', skyid: null },
  { targetWord: 'oficina de correos', translating: 'почта', skyid: null },
  { targetWord: 'estación', translating: 'станция, вокзал', skyid: null },
  { targetWord: 'centro', translating: 'центр', skyid: null },
  { targetWord: 'tienda', translating: 'магазин', skyid: null },
  { targetWord: 'montaña', translating: 'гора', skyid: null },
  { targetWord: 'apartamento', translating: 'квартира', skyid: null },
  { targetWord: 'cocina', translating: 'кухня', skyid: null },
  { targetWord: 'balcón', translating: 'балкон', skyid: null },
  { targetWord: 'cuarto de baño', translating: 'ванная', skyid: null },
  { targetWord: 'ducha', translating: 'душ', skyid: null },
  { targetWord: 'inodoro', translating: 'туалет', skyid: null },
  { targetWord: 'suelo', translating: 'пол', skyid: null },
  { targetWord: 'techo', translating: 'потолок', skyid: null },
  { targetWord: 'piso', translating: 'этаж', skyid: null },
  { targetWord: 'pasillo', translating: 'коридор', skyid: null },
  { targetWord: 'dormitorio', translating: 'спальня', skyid: null },
  { targetWord: 'sala de estar', translating: 'зал', skyid: null },
  { targetWord: 'puerta', translating: 'дверь', skyid: null },
  { targetWord: 'ventana', translating: 'окно', skyid: null },
  { targetWord: 'llave', translating: 'ключ', skyid: null },
  { targetWord: 'cama', translating: 'кровать', skyid: null },
  { targetWord: 'almohada', translating: 'подушка', skyid: null },
  { targetWord: 'mesa', translating: 'стол', skyid: null },
  { targetWord: 'silla', translating: 'стул', skyid: null },
  { targetWord: 'sillón', translating: 'кресло', skyid: null },
  { targetWord: 'nevera', translating: 'холодильник', skyid: null },
  { targetWord: 'sofá', translating: 'диван', skyid: null },
  { targetWord: 'espejo', translating: 'зеркало', skyid: null },
  { targetWord: 'comida', translating: 'еда', skyid: null },
  { targetWord: 'pan', translating: 'хлеб', skyid: null },
  { targetWord: 'mantequilla', translating: 'масло', skyid: null },
  { targetWord: 'queso', translating: 'сыр', skyid: null },
  { targetWord: 'salchichón', translating: 'колбаса', skyid: null },
  { targetWord: 'aceite', translating: 'растительное масло', skyid: null },
  { targetWord: 'pimienta', translating: 'горький перец', skyid: null },
  { targetWord: 'sal', translating: 'соль', skyid: null },
  { targetWord: 'baya', translating: 'ягода', skyid: null },
  { targetWord: 'miel', translating: 'мёд', skyid: null },
  { targetWord: 'mermelada', translating: 'варенье', skyid: null },
  { targetWord: 'seta', translating: 'гриб', skyid: null },
  { targetWord: 'cebolla', translating: 'лук (репчатый)', skyid: null },
  { targetWord: 'banana', translating: 'банан', skyid: null },
  { targetWord: 'zanahoria', translating: 'морковь', skyid: null },
  { targetWord: 'pera', translating: 'груша', skyid: null },
  { targetWord: 'remolacha', translating: 'свекла', skyid: null },
  { targetWord: 'fruta', translating: 'фрукты', skyid: null },
  { targetWord: 'melón', translating: 'дыня', skyid: null },
  { targetWord: 'sandía', translating: 'арбуз', skyid: null },
  { targetWord: 'pastel', translating: 'пирожное, пирожок', skyid: null },
  { targetWord: 'tarta', translating: 'торт', skyid: null },
  { targetWord: 'chocolate', translating: 'шоколад', skyid: null },
  { targetWord: 'carne', translating: 'мясо', skyid: null },
  { targetWord: 'patatas', translating: 'картофель', skyid: null },
  { targetWord: 'ensalada', translating: 'салат', skyid: null },
  { targetWord: 'tomate', translating: 'помидор', skyid: null },
  { targetWord: 'pepino', translating: 'огурец', skyid: null },
  { targetWord: 'col', translating: 'капуста', skyid: null },
  { targetWord: 'papilla', translating: 'каша', skyid: null },
  { targetWord: 'sopa', translating: 'суп', skyid: null },
  { targetWord: 'bocadillo', translating: 'бутерброд', skyid: null },
  { targetWord: 'soda', translating: 'газировка', skyid: null },
  { targetWord: 'agua', translating: 'вода', skyid: null },
  { targetWord: 'té', translating: 'чай', skyid: null },
  { targetWord: 'leche', translating: 'молоко', skyid: null },
  { targetWord: 'jugo', translating: 'сок', skyid: null },
  { targetWord: 'manzana', translating: 'яблоко', skyid: null },
  { targetWord: 'uvas', translating: 'виноград', skyid: null },
  { targetWord: 'naranja', translating: 'апельсин', skyid: null },
  { targetWord: 'piña', translating: 'ананас', skyid: null },
  { targetWord: 'albaricoque', translating: 'абрикос', skyid: null },
  { targetWord: 'azúcar', translating: 'сахар', skyid: null },
  { targetWord: 'arroz', translating: 'рис', skyid: null },
  { targetWord: 'fideos', translating: 'лапша', skyid: null },
  { targetWord: 'res', translating: 'говядина', skyid: null },
  { targetWord: 'cerdo', translating: 'свинина', skyid: null },
  { targetWord: 'pollo', translating: 'курица', skyid: null },
  { targetWord: 'chuleta', translating: 'котлета', skyid: null },
  { targetWord: 'limón', translating: 'лимон', skyid: null },
  { targetWord: 'guisante', translating: 'горох', skyid: null },
  { targetWord: 'bollo', translating: 'булочка', skyid: null },
  { targetWord: 'pescado', translating: 'рыба', skyid: null },
  { targetWord: 'caramelo', translating: 'конфета', skyid: null },
  { targetWord: 'helado', translating: 'мороженое', skyid: null },
  { targetWord: 'nuez', translating: 'орех', skyid: null },
  { targetWord: 'huevo', translating: 'яйцо', skyid: null },
  { targetWord: 'melocotón', translating: 'персик', skyid: null },
  { targetWord: 'taza', translating: 'чашка', skyid: null },
  { targetWord: 'vaso', translating: 'стакан', skyid: null },
  { targetWord: 'plato', translating: 'тарелка', skyid: null },
  { targetWord: 'cuchara', translating: 'ложка', skyid: null },
  { targetWord: 'tenedor', translating: 'вилка', skyid: null },
  { targetWord: 'cuchillo', translating: 'нож', skyid: null },
  { targetWord: 'platillo', translating: 'блюдце', skyid: null },
  { targetWord: 'botella', translating: 'бутылка', skyid: null },
  { targetWord: 'servilleta', translating: 'салфетка', skyid: null },
  { targetWord: 'desayuno', translating: 'завтрак', skyid: null },
  { targetWord: 'almuerzo', translating: 'обед', skyid: null },
  { targetWord: 'cena', translating: 'ужин', skyid: null },
  { targetWord: 'avión', translating: 'самолет', skyid: null },
  { targetWord: 'coche', translating: 'автомобиль', skyid: null },
  { targetWord: 'tranvía', translating: 'трамвай', skyid: null },
  { targetWord: 'autobús', translating: 'автобус', skyid: null },
  { targetWord: 'tren', translating: 'поезд', skyid: null },
  { targetWord: 'bicicleta', translating: 'велосипед', skyid: null },
  { targetWord: 'tiempo', translating: 'время, погода', skyid: null },
  { targetWord: 'año', translating: 'год', skyid: null },
  { targetWord: 'semana', translating: 'неделя', skyid: null },
  { targetWord: 'hora', translating: 'час', skyid: null },
  { targetWord: 'minuto', translating: 'минута', skyid: null },
  { targetWord: 'ayer', translating: 'вчера', skyid: null },
  { targetWord: 'hoy', translating: 'сегодня', skyid: null },
  { targetWord: 'mañana', translating: 'завтра, утро', skyid: null },
  { targetWord: 'fiesta', translating: 'праздник; вечеринка', skyid: null },
  { targetWord: 'vez', translating: 'раз', skyid: null },
  { targetWord: 'día', translating: 'день', skyid: null },
  { targetWord: 'tarde', translating: 'вечер', skyid: null },
  { targetWord: 'noche', translating: 'ночь', skyid: null },
  { targetWord: 'lunes', translating: 'понедельник', skyid: null },
  { targetWord: 'martes', translating: 'вторник', skyid: null },
  { targetWord: 'miércoles', translating: 'среда', skyid: null },
  { targetWord: 'jueves', translating: 'четверг', skyid: null },
  { targetWord: 'viernes', translating: 'пятница', skyid: null },
  { targetWord: 'sábado', translating: 'суббота', skyid: null },
  { targetWord: 'domingo', translating: 'воскресенье', skyid: null },
  { targetWord: 'mes', translating: 'месяц', skyid: null },
  { targetWord: 'enero', translating: 'январь', skyid: null },
  { targetWord: 'febrero', translating: 'февраль', skyid: null },
  { targetWord: 'marzo', translating: 'март', skyid: null },
  { targetWord: 'abril', translating: 'апрель', skyid: null },
  { targetWord: 'mayo', translating: 'май', skyid: null },
  { targetWord: 'junio', translating: 'июнь', skyid: null },
  { targetWord: 'julio', translating: 'июль', skyid: null },
  { targetWord: 'agosto', translating: 'август', skyid: null },
  { targetWord: 'septiembre', translating: 'сентябрь', skyid: null },
  { targetWord: 'octubre', translating: 'октябрь', skyid: null },
  { targetWord: 'noviembre', translating: 'ноябрь', skyid: null },
  { targetWord: 'diciembre', translating: 'декабрь', skyid: null },
  { targetWord: 'primavera', translating: 'весна', skyid: null },
  { targetWord: 'verano', translating: 'лето', skyid: null },
  { targetWord: 'otoño', translating: 'осень', skyid: null },
  { targetWord: 'invierno', translating: 'зима', skyid: null },
  { targetWord: 'nombre', translating: 'имя, фамилия', skyid: null },
  { targetWord: 'dirección', translating: 'адрес', skyid: null },
  { targetWord: 'número', translating: 'номер', skyid: null },
  { targetWord: 'cumpleaños', translating: 'день рождения', skyid: null },
  { targetWord: 'casado⁄a', translating: 'женатый ⁄ замужняя', skyid: null },
  { targetWord: 'cosa', translating: 'вещь', skyid: null },
  { targetWord: 'pluma', translating: 'ручка', skyid: null },
  { targetWord: 'libro', translating: 'книга', skyid: null },
  { targetWord: 'ajedrez', translating: 'шахматы', skyid: null },
  { targetWord: 'teléfono', translating: 'телефон', skyid: null },
  { targetWord: 'reloj', translating: 'часы', skyid: null },
  { targetWord: 'peine', translating: 'расчёска', skyid: null },
  { targetWord: 'televisor', translating: 'телевизор', skyid: null },
  { targetWord: 'plancha', translating: 'утюг', skyid: null },
  { targetWord: 'jabón', translating: 'мыло', skyid: null },
  { targetWord: 'radio', translating: 'радио', skyid: null },
  { targetWord: 'bolsa', translating: 'сумка', skyid: null },
  { targetWord: 'mapa', translating: 'карта; открытка', skyid: null },
  { targetWord: 'maleta', translating: 'чемодан', skyid: null },
  { targetWord: 'regalo', translating: 'подарок', skyid: null },
  {
    targetWord: 'cámara',
    translating: 'фотоаппарат; видеокамера',
    skyid: null
  },
  { targetWord: 'ordenador', translating: 'компьютер', skyid: null },
  { targetWord: 'película', translating: 'фильм; плёнка', skyid: null },
  { targetWord: 'flor', translating: 'цветок', skyid: null },
  { targetWord: 'florero', translating: 'ваза', skyid: null },
  { targetWord: 'cuadro', translating: 'картина', skyid: null },
  { targetWord: 'pañuelo', translating: 'носовой платок', skyid: null },
  { targetWord: 'bola', translating: 'мяч', skyid: null },
  { targetWord: 'globo', translating: 'воздушный шар(ик)', skyid: null },
  { targetWord: 'juguete', translating: 'игрушка', skyid: null },
  { targetWord: 'cuenta', translating: 'счёт', skyid: null },
  { targetWord: 'sobre', translating: 'конверт', skyid: null },
  { targetWord: 'papel', translating: 'бумага', skyid: null },
  { targetWord: 'periódico', translating: 'газета', skyid: null },
  { targetWord: 'carta', translating: 'письмо', skyid: null },
  { targetWord: 'billete', translating: 'билет', skyid: null },
  { targetWord: 'ropa', translating: 'одежда', skyid: null },
  { targetWord: 'zapatos', translating: 'обувь', skyid: null },
  { targetWord: 'abrigo', translating: 'пальто', skyid: null },
  { targetWord: 'vestido', translating: 'платье', skyid: null },
  { targetWord: 'camisa', translating: 'рубашка', skyid: null },
  { targetWord: 'falda', translating: 'юбка', skyid: null },
  { targetWord: 'guante', translating: 'перчатка', skyid: null },
  { targetWord: 'sombrero', translating: 'шляпа', skyid: null },
  { targetWord: 'chaqueta', translating: 'пиджак, куртка', skyid: null },
  { targetWord: 'bufanda', translating: 'шарф', skyid: null },
  { targetWord: 'calcetín', translating: 'носок', skyid: null },
  { targetWord: 'suéter', translating: 'свитер', skyid: null },
  { targetWord: 'camiseta', translating: 'футболка', skyid: null },
  { targetWord: 'corbata', translating: 'галстук', skyid: null },
  { targetWord: 'pantalones', translating: 'брюки', skyid: null },
  { targetWord: 'mano', translating: 'рука', skyid: null },
  { targetWord: 'pie', translating: 'нога', skyid: null },
  { targetWord: 'cabeza', translating: 'голова', skyid: null },
  { targetWord: 'ojo', translating: 'глаз', skyid: null },
  { targetWord: 'lengua', translating: 'язык', skyid: null },
  { targetWord: 'nariz', translating: 'нос', skyid: null },
  { targetWord: 'boca', translating: 'рот', skyid: null },
  { targetWord: 'oreja', translating: 'ухо', skyid: null },
  { targetWord: 'qué', translating: 'что, какой', skyid: null },
  { targetWord: 'cual', translating: 'какой', skyid: null },
  { targetWord: 'quién', translating: 'кто', skyid: null },
  { targetWord: 'dónde', translating: 'где', skyid: null },
  { targetWord: 'a dónde', translating: 'куда', skyid: null },
  { targetWord: 'de dónde', translating: 'откуда', skyid: null },
  { targetWord: 'cómo', translating: 'как', skyid: null },
  { targetWord: 'por qué', translating: 'почему', skyid: null },
  { targetWord: 'cuándo', translating: 'когда', skyid: null },
  { targetWord: 'yo', translating: 'я', skyid: null },
  { targetWord: 'tú', translating: 'ты', skyid: null },
  { targetWord: 'él', translating: 'он', skyid: null },
  { targetWord: 'ella', translating: 'она', skyid: null },
  { targetWord: 'usted(es)', translating: 'Вы (ед.ч.⁄мн.ч.)', skyid: null },
  { targetWord: 'nosotros', translating: 'мы', skyid: null },
  { targetWord: 'vosotros', translating: 'вы', skyid: null },
  { targetWord: 'ellos⁄as', translating: 'они', skyid: null },
  { targetWord: 'mi', translating: 'мой', skyid: null },
  { targetWord: 'tu', translating: 'твой', skyid: null },
  { targetWord: 'su', translating: 'его, ее, их, Ваш', skyid: null },
  { targetWord: 'nuestro', translating: 'наш', skyid: null },
  { targetWord: 'vuestro', translating: 'ваш', skyid: null },
  { targetWord: 'de', translating: 'из; передает род. падеж', skyid: null },
  { targetWord: 'a', translating: 'к', skyid: null },
  { targetWord: 'sobre', translating: 'на', skyid: null },
  { targetWord: 'debajo de', translating: 'под', skyid: null },
  { targetWord: 'detrás de', translating: 'позади', skyid: null },
  { targetWord: 'con', translating: 'с', skyid: null },
  { targetWord: 'sin', translating: 'без', skyid: null },
  { targetWord: 'antes de', translating: 'до, прежде', skyid: null },
  { targetWord: 'después de', translating: 'после', skyid: null },
  { targetWord: 'delante de', translating: 'перед', skyid: null },
  { targetWord: 'entre', translating: 'между', skyid: null },
  { targetWord: 'en', translating: 'в', skyid: null },
  { targetWord: 'cerca de', translating: 'возле', skyid: null },
  { targetWord: 'para', translating: 'для', skyid: null },
  { targetWord: 'uno', translating: 'один', skyid: null },
  { targetWord: 'dos', translating: 'два', skyid: null },
  { targetWord: 'tres', translating: 'три', skyid: null },
  { targetWord: 'cuatro', translating: 'четыре', skyid: null },
  { targetWord: 'cinco', translating: 'пять', skyid: null },
  { targetWord: 'seis', translating: 'шесть', skyid: null },
  { targetWord: 'siete', translating: 'семь', skyid: null },
  { targetWord: 'ocho', translating: 'восемь', skyid: null },
  { targetWord: 'nueve', translating: 'девять', skyid: null },
  { targetWord: 'diez', translating: 'десять', skyid: null },
  { targetWord: 'once', translating: 'одиннадцать', skyid: null },
  { targetWord: 'doce', translating: 'двенадцать', skyid: null },
  { targetWord: 'trece', translating: 'тринадцать', skyid: null },
  { targetWord: 'catorce', translating: 'четырнадцать', skyid: null },
  { targetWord: 'quince', translating: 'пятнадцать', skyid: null },
  { targetWord: 'dieciséis', translating: 'шестнадцать', skyid: null },
  { targetWord: 'diecisiete', translating: 'семнадцать', skyid: null },
  { targetWord: 'dieciocho', translating: 'восемнадцать', skyid: null },
  { targetWord: 'diecinueve', translating: 'девятнадцать', skyid: null },
  { targetWord: 'veinte', translating: 'двадцать', skyid: null },
  { targetWord: 'treinta', translating: 'тридцать', skyid: null },
  { targetWord: 'cuarenta', translating: 'сорок', skyid: null },
  { targetWord: 'cincuenta', translating: 'пятьдесят', skyid: null },
  { targetWord: 'sesenta', translating: 'шестьдесят', skyid: null },
  { targetWord: 'setenta', translating: 'семьдесят', skyid: null },
  { targetWord: 'ochenta', translating: 'восемьдесят', skyid: null },
  { targetWord: 'noventa', translating: 'девяносто', skyid: null },
  { targetWord: 'ciento', translating: 'сто', skyid: null },
  { targetWord: 'mil', translating: 'тысяча', skyid: null },
  { targetWord: 'viejo- старый', skyid: null },
  { targetWord: 'joven', translating: 'молодой', skyid: null },
  { targetWord: 'nuevo', translating: 'новый', skyid: null },
  { targetWord: 'grande', translating: 'большой', skyid: null },
  { targetWord: 'pequeño', translating: 'маленький', skyid: null },
  { targetWord: 'hambriento', translating: 'голодный', skyid: null },
  { targetWord: 'bueno', translating: 'хороший', skyid: null },
  { targetWord: 'malo', translating: 'плохой', skyid: null },
  { targetWord: 'bien', translating: 'хорошо', skyid: null },
  { targetWord: 'mal', translating: 'плохо', skyid: null },
  { targetWord: 'temprano', translating: 'ранний', skyid: null },
  { targetWord: 'tarde', translating: 'поздний', skyid: null },
  { targetWord: 'pasado', translating: 'последний, прошлый', skyid: null },
  { targetWord: 'próximo', translating: 'следующий', skyid: null },
  { targetWord: 'libre', translating: 'свободный', skyid: null },
  { targetWord: 'caliente', translating: 'тёплый, горячий', skyid: null },
  { targetWord: 'frío', translating: 'холодный', skyid: null },
  { targetWord: 'alto', translating: 'высокий', skyid: null },
  { targetWord: 'bajo', translating: 'низкий', skyid: null },
  { targetWord: 'largo', translating: 'длинный, долгий', skyid: null },
  { targetWord: 'corto', translating: 'короткий', skyid: null },
  { targetWord: 'fácil', translating: 'лёгкий, несложный', skyid: null },
  { targetWord: 'difícil', translating: 'тяжёлый, трудный', skyid: null },
  { targetWord: 'ligero', translating: 'легкий (по весу)', skyid: null },
  { targetWord: 'pesado', translating: 'тяжелый (по весу)', skyid: null },
  { targetWord: 'oscuro', translating: 'тёмный', skyid: null },
  { targetWord: 'claro', translating: 'светлый', skyid: null },
  { targetWord: 'caro', translating: 'дорогой', skyid: null },
  { targetWord: 'barato', translating: 'дешёвый', skyid: null },
  { targetWord: 'a la izquierda', translating: 'cлева', skyid: null },
  { targetWord: 'a la derecha', translating: 'справа', skyid: null },
  { targetWord: 'correcto', translating: 'правильный', skyid: null },
  { targetWord: 'rápido', translating: 'быстрый', skyid: null },
  { targetWord: 'despacio', translating: 'медленный', skyid: null },
  { targetWord: 'suave', translating: 'мягкий', skyid: null },
  { targetWord: 'duro', translating: 'твёрдый', skyid: null },
  { targetWord: 'bonito', translating: 'красивый', skyid: null },
  { targetWord: 'atento', translating: 'внимательный', skyid: null },
  { targetWord: 'triste', translating: 'печальный', skyid: null },
  { targetWord: 'alegre', translating: 'радостный', skyid: null },
  { targetWord: 'feliz', translating: 'счастливый', skyid: null },
  { targetWord: 'listo', translating: 'готовый', skyid: null },
  { targetWord: 'enojado', translating: 'сердитый', skyid: null },
  { targetWord: 'principal', translating: 'основной, главный', skyid: null },
  { targetWord: 'negro', translating: 'чёрный', skyid: null },
  { targetWord: 'azul', translating: 'голубой; синий', skyid: null },
  { targetWord: 'marrón', translating: 'коричневый', skyid: null },
  { targetWord: 'verde', translating: 'зелёный', skyid: null },
  { targetWord: 'gris', translating: 'серый', skyid: null },
  { targetWord: 'rojo', translating: 'красный', skyid: null },
  { targetWord: 'blanco', translating: 'белый', skyid: null },
  { targetWord: 'amarillo', translating: 'жёлтый', skyid: null },
  { targetWord: 'sí', translating: 'да', skyid: null },
  { targetWord: 'no', translating: 'нет; не', skyid: null },
  { targetWord: 'este', translating: 'этот', skyid: null },
  { targetWord: 'ese', translating: 'тот', skyid: null },
  { targetWord: 'aquel', translating: 'тот (дальше чем ese)', skyid: null },
  { targetWord: 'que', translating: 'что (союз)', skyid: null },
  { targetWord: 'aquí', translating: 'здесь', skyid: null },
  { targetWord: 'allí', translating: 'там', skyid: null },
  { targetWord: 'acá- сюда', skyid: null },
  { targetWord: 'allá', translating: 'туда', skyid: null },
  { targetWord: 'ahora', translating: 'сейчас, теперь', skyid: null },
  { targetWord: 'ya', translating: 'уже', skyid: null },
  { targetWord: 'todavía', translating: 'еще', skyid: null },
  { targetWord: 'mucho⁄a⁄s', translating: 'много', skyid: null },
  { targetWord: 'poco⁄a⁄s', translating: 'мало', skyid: null },
  { targetWord: 'muy', translating: 'очень', skyid: null },
  { targetWord: 'cada', translating: 'каждый', skyid: null },
  { targetWord: 'todos', translating: 'все', skyid: null },
  { targetWord: 'todo', translating: 'всё', skyid: null },
  { targetWord: 'tan', translating: 'так', skyid: null },
  { targetWord: 'también', translating: 'так же, тоже', skyid: null },
  { targetWord: 'y', translating: 'и', skyid: null },
  { targetWord: 'o', translating: 'или', skyid: null },
  { targetWord: 'pero', translating: 'но', skyid: null },
  { targetWord: 'porque', translating: 'потому что, так как', skyid: null },
  { targetWord: 'ser', translating: 'быть, являться', skyid: null },
  {
    targetWord: 'estar',
    translating: 'быть, находиться, стоять',
    skyid: null
  },
  { targetWord: 'tener', translating: 'иметь', skyid: null },
  { targetWord: 'poder', translating: 'мочь', skyid: null },
  { targetWord: 'deber', translating: 'должен', skyid: null },
  { targetWord: 'vivir', translating: 'жить', skyid: null },
  {
    targetWord: 'permanecer',
    translating: 'оставаться, останавливаться',
    skyid: null
  },
  { targetWord: 'venir', translating: 'приходить, приезжать', skyid: null },
  { targetWord: 'ir', translating: 'идти, ехать', skyid: null },
  { targetWord: 'ver', translating: 'видеть', skyid: null },
  { targetWord: 'sentar', translating: 'сидеть', skyid: null },
  { targetWord: 'decir', translating: 'сказать', skyid: null },
  { targetWord: 'hablar', translating: 'разговаривать', skyid: null },
  { targetWord: 'trabajar', translating: 'работать', skyid: null },
  { targetWord: 'romper', translating: 'ломать', skyid: null },
  { targetWord: 'hacer', translating: 'делать', skyid: null },
  { targetWord: 'enviar', translating: 'посылать', skyid: null },
  { targetWord: 'comprar', translating: 'покупать', skyid: null },
  { targetWord: 'nadar', translating: 'плавать', skyid: null },
  { targetWord: 'dormir', translating: 'спать', skyid: null },
  { targetWord: 'despertar', translating: 'будить', skyid: null },
  { targetWord: 'lavar', translating: 'мыть, cтирать', skyid: null },
  { targetWord: 'probar', translating: 'пробовать', skyid: null },
  { targetWord: 'encontrar', translating: 'находить', skyid: null },
  { targetWord: 'traer', translating: 'приносить, привозить', skyid: null },
  { targetWord: 'celebrar', translating: 'праздновать', skyid: null },
  { targetWord: 'sonreír', translating: 'улыбаться', skyid: null },
  { targetWord: 'llorar', translating: 'плакать', skyid: null },
  { targetWord: 'costar', translating: 'стоить', skyid: null },
  { targetWord: 'aprender', translating: 'учиться', skyid: null },
  { targetWord: 'enseñar', translating: 'обучать', skyid: null },
  { targetWord: 'escribir', translating: 'писать', skyid: null },
  { targetWord: 'cambiar', translating: 'менять', skyid: null },
  { targetWord: 'caer', translating: 'падать', skyid: null },
  { targetWord: 'escuchar', translating: 'слушать', skyid: null },
  { targetWord: 'mostrar', translating: 'показывать', skyid: null },
  { targetWord: 'ganar', translating: 'побеждать', skyid: null },
  { targetWord: 'pensar', translating: 'думать', skyid: null },
  { targetWord: 'cerrar', translating: 'закрывать', skyid: null },
  { targetWord: 'abrir', translating: 'открывать', skyid: null },
  { targetWord: 'saber', translating: 'знать', skyid: null },
  { targetWord: 'conocer', translating: 'быть знакомым', skyid: null },
  { targetWord: 'cantar', translating: 'петь', skyid: null },
  { targetWord: 'bailar', translating: 'танцевать', skyid: null },
  { targetWord: 'preguntar', translating: 'спрашивать', skyid: null },
  { targetWord: 'contestar', translating: 'отвечать', skyid: null },
  { targetWord: 'recoger', translating: 'собирать', skyid: null },
  { targetWord: 'amar', translating: 'любить', skyid: null },
  { targetWord: 'dibujar', translating: 'рисовать', skyid: null },
  { targetWord: 'elegir', translating: 'выбирать', skyid: null },
  { targetWord: 'querer', translating: 'хотеть', skyid: null },
  { targetWord: 'comer', translating: 'кушать', skyid: null },
  { targetWord: 'beber', translating: 'пить', skyid: null },
  { targetWord: 'dar', translating: 'давать', skyid: null },
  { targetWord: 'hornear', translating: 'печь', skyid: null },
  { targetWord: 'cocinar', translating: 'готовить (еду)', skyid: null },
  { targetWord: 'cortar', translating: 'резать', skyid: null },
  { targetWord: 'tomar', translating: 'брать', skyid: null },
  { targetWord: 'esperar', translating: 'ждать', skyid: null },
  { targetWord: 'leer', translating: 'читать', skyid: null },
  { targetWord: 'jugar', translating: 'играть', skyid: null },
  { targetWord: 'fumar', translating: 'курить', skyid: null },
  { targetWord: 'crear', translating: 'создавать', skyid: null },
  { targetWord: 'luchar', translating: 'бороться; драться', skyid: null },
  { targetWord: 'gracias', translating: 'спасибо', skyid: null },
  { targetWord: 'perdón', translating: 'извини(те)', skyid: null },
  {
    targetWord: 'por favor',
    translating: 'пожалуйста (прошу)',
    skyid: null
  },
  {
    targetWord: 'de nada',
    translating: 'пожалуйста, не за что',
    skyid: null
  },
  { targetWord: 'qué lástima', translating: 'жаль', skyid: null },
  { targetWord: 'hasta la vista', translating: 'до свидания', skyid: null },
  { targetWord: 'canción', translating: 'песня', skyid: null },
  { targetWord: 'música', translating: 'музыка', skyid: null },
  { targetWord: 'tamaño', translating: 'размер', skyid: null },
  { targetWord: 'dinero', translating: 'деньги', skyid: null },
  { targetWord: 'felicidad', translating: 'счастье', skyid: null },
  { targetWord: 'suerte', translating: 'удача', skyid: null },
  { targetWord: 'broma', translating: 'шутка', skyid: null },
  { targetWord: 'sorpresa', translating: 'сюрприз', skyid: null },
  { targetWord: 'problema', translating: 'проблема', skyid: null },
  { targetWord: 'lluvia', translating: 'дождь', skyid: null },
  { targetWord: 'viento', translating: 'ветер', skyid: null },
  { targetWord: 'nieve', translating: 'снег', skyid: null },
  { targetWord: 'cielo', translating: 'небо	' }
];
