export const myBase = [
  { targetWord: 'gente', translating: 'люди' },
  { targetWord: 'persona', translating: 'человек' },
  { targetWord: 'hombre', translating: 'мужчина' },
  { targetWord: 'marido', translating: 'муж' },
  { targetWord: 'mujer', translating: 'женщина, жена' },
  { targetWord: 'niño', translating: 'ребенок' },
  { targetWord: 'muchacho⁄a', translating: 'мальчик⁄девочка' },
  { targetWord: 'amigo', translating: 'друг' },
  { targetWord: 'invitado', translating: 'гость' },
  { targetWord: 'familia', translating: 'семья' },
  { targetWord: 'padres', translating: 'родители' },
  { targetWord: 'padre', translating: 'отец' },
  { targetWord: 'madre', translating: 'мать' },
  { targetWord: 'hijo⁄a', translating: 'сын⁄дочь' },
  { targetWord: 'abuelo⁄a', translating: 'дед⁄бабушка' },
  { targetWord: 'suegro⁄a', translating: 'тесть (свекор)⁄теща (свекровь)' },
  { targetWord: 'tío⁄a', translating: 'дядя⁄тетя' },
  { targetWord: 'hermano⁄a', translating: 'брат⁄сестра' },
  { targetWord: 'primo⁄a', translating: 'двоюродный брат⁄сестра' },
  { targetWord: 'trabajo', translating: 'работа' },
  { targetWord: 'maestro', translating: 'учитель' },
  { targetWord: 'conductor', translating: 'водитель' },
  { targetWord: 'obrero', translating: 'рабочий' },
  { targetWord: 'ingeniero', translating: 'инженер' },
  { targetWord: 'doctor', translating: 'врач' },
  { targetWord: 'enfermera', translating: 'медсестра' },
  { targetWord: 'vendedor', translating: 'продавец' },
  { targetWord: 'contador', translating: 'бухгалтер' },
  { targetWord: 'pintor', translating: 'художник' },
  { targetWord: 'estudiante', translating: 'студент' },
  { targetWord: 'país', translating: 'страна' },
  { targetWord: 'Rusia', translating: 'Россия' },
  { targetWord: 'España', translating: 'Испания' },
  { targetWord: 'animal', translating: 'животное' },
  { targetWord: 'gato', translating: 'кошка' },
  { targetWord: 'perro', translating: 'собака' },
  { targetWord: 'pájaro', translating: 'птица' },
  { targetWord: 'ciudad', translating: 'город' },
  { targetWord: 'escuela', translating: 'школа' },
  { targetWord: 'teatro', translating: 'театр' },
  { targetWord: 'calle', translating: 'улица' },
  { targetWord: 'plaza', translating: 'площадь' },
  { targetWord: 'lugar', translating: 'место' },
  { targetWord: 'casa', translating: 'дом' },
  { targetWord: 'iglesia', translating: 'церковь' },
  { targetWord: 'río', translating: 'река' },
  { targetWord: 'café', translating: 'кафе, кофе' },
  { targetWord: 'hotel', translating: 'гостиница' },
  { targetWord: 'jardín', translating: 'сад' },
  { targetWord: 'parque', translating: 'парк' },
  { targetWord: 'banco', translating: 'банк' },
  { targetWord: 'parada', translating: 'остановка' },
  { targetWord: 'cine', translating: 'кинотеатр' },
  { targetWord: 'puente', translating: 'мост' },
  { targetWord: 'intersección', translating: 'перекрёсток' },
  { targetWord: 'bosque', translating: 'лес' },
  { targetWord: 'hospital', translating: 'больница' },
  { targetWord: 'mercado', translating: 'рынок' },
  { targetWord: 'policía', translating: 'полиция' },
  { targetWord: 'oficina de correos', translating: 'почта' },
  { targetWord: 'estación', translating: 'станция, вокзал' },
  { targetWord: 'centro', translating: 'центр' },
  { targetWord: 'tienda', translating: 'магазин' },
  { targetWord: 'montaña', translating: 'гора' },
  { targetWord: 'apartamento', translating: 'квартира' },
  { targetWord: 'cocina', translating: 'кухня' },
  { targetWord: 'balcón', translating: 'балкон' },
  { targetWord: 'cuarto de baño', translating: 'ванная' },
  { targetWord: 'ducha', translating: 'душ' },
  { targetWord: 'inodoro', translating: 'туалет' },
  { targetWord: 'suelo', translating: 'пол' },
  { targetWord: 'techo', translating: 'потолок' },
  { targetWord: 'piso', translating: 'этаж' },
  { targetWord: 'pasillo', translating: 'коридор' },
  { targetWord: 'dormitorio', translating: 'спальня' },
  { targetWord: 'sala de estar', translating: 'зал' },
  { targetWord: 'puerta', translating: 'дверь' },
  { targetWord: 'ventana', translating: 'окно' },
  { targetWord: 'llave', translating: 'ключ' },
  { targetWord: 'cama', translating: 'кровать' },
  { targetWord: 'almohada', translating: 'подушка' },
  { targetWord: 'mesa', translating: 'стол' },
  { targetWord: 'silla', translating: 'стул' },
  { targetWord: 'sillón', translating: 'кресло' },
  { targetWord: 'nevera', translating: 'холодильник' },
  { targetWord: 'sofá', translating: 'диван' },
  { targetWord: 'espejo', translating: 'зеркало' },
  { targetWord: 'comida', translating: 'еда' },
  { targetWord: 'pan', translating: 'хлеб' },
  { targetWord: 'mantequilla', translating: 'масло' },
  { targetWord: 'queso', translating: 'сыр' },
  { targetWord: 'salchichón', translating: 'колбаса' },
  { targetWord: 'aceite', translating: 'растительное масло' },
  { targetWord: 'pimienta', translating: 'горький перец' },
  { targetWord: 'sal', translating: 'соль' },
  { targetWord: 'baya', translating: 'ягода' },
  { targetWord: 'miel', translating: 'мёд' },
  { targetWord: 'mermelada', translating: 'варенье' },
  { targetWord: 'seta', translating: 'гриб' },
  { targetWord: 'cebolla', translating: 'лук (репчатый)' },
  { targetWord: 'banana', translating: 'банан' },
  { targetWord: 'zanahoria', translating: 'морковь' },
  { targetWord: 'pera', translating: 'груша' },
  { targetWord: 'remolacha', translating: 'свекла' },
  { targetWord: 'fruta', translating: 'фрукты' },
  { targetWord: 'melón', translating: 'дыня' },
  { targetWord: 'sandía', translating: 'арбуз' },
  { targetWord: 'pastel', translating: 'пирожное, пирожок' },
  { targetWord: 'tarta', translating: 'торт' },
  { targetWord: 'chocolate', translating: 'шоколад' },
  { targetWord: 'carne', translating: 'мясо' },
  { targetWord: 'patatas', translating: 'картофель' },
  { targetWord: 'ensalada', translating: 'салат' },
  { targetWord: 'tomate', translating: 'помидор' },
  { targetWord: 'pepino', translating: 'огурец' },
  { targetWord: 'col', translating: 'капуста' },
  { targetWord: 'papilla', translating: 'каша' },
  { targetWord: 'sopa', translating: 'суп' },
  { targetWord: 'bocadillo', translating: 'бутерброд' },
  { targetWord: 'soda', translating: 'газировка' },
  { targetWord: 'agua', translating: 'вода' },
  { targetWord: 'té', translating: 'чай' },
  { targetWord: 'leche', translating: 'молоко' },
  { targetWord: 'jugo', translating: 'сок' },
  { targetWord: 'manzana', translating: 'яблоко' },
  { targetWord: 'uvas', translating: 'виноград' },
  { targetWord: 'naranja', translating: 'апельсин' },
  { targetWord: 'piña', translating: 'ананас' },
  { targetWord: 'albaricoque', translating: 'абрикос' },
  { targetWord: 'azúcar', translating: 'сахар' },
  { targetWord: 'arroz', translating: 'рис' },
  { targetWord: 'fideos', translating: 'лапша' },
  { targetWord: 'res', translating: 'говядина' },
  { targetWord: 'cerdo', translating: 'свинина' },
  { targetWord: 'pollo', translating: 'курица' },
  { targetWord: 'chuleta', translating: 'котлета' },
  { targetWord: 'limón', translating: 'лимон' },
  { targetWord: 'guisante', translating: 'горох' },
  { targetWord: 'bollo', translating: 'булочка' },
  { targetWord: 'pescado', translating: 'рыба' },
  { targetWord: 'caramelo', translating: 'конфета' },
  { targetWord: 'helado', translating: 'мороженое' },
  { targetWord: 'nuez', translating: 'орех' },
  { targetWord: 'huevo', translating: 'яйцо' },
  { targetWord: 'melocotón', translating: 'персик' },
  { targetWord: 'taza', translating: 'чашка' },
  { targetWord: 'vaso', translating: 'стакан' },
  { targetWord: 'plato', translating: 'тарелка' },
  { targetWord: 'cuchara', translating: 'ложка' },
  { targetWord: 'tenedor', translating: 'вилка' },
  { targetWord: 'cuchillo', translating: 'нож' },
  { targetWord: 'platillo', translating: 'блюдце' },
  { targetWord: 'botella', translating: 'бутылка' },
  { targetWord: 'servilleta', translating: 'салфетка' },
  { targetWord: 'desayuno', translating: 'завтрак' },
  { targetWord: 'almuerzo', translating: 'обед' },
  { targetWord: 'cena', translating: 'ужин' },
  { targetWord: 'avión', translating: 'самолет' },
  { targetWord: 'coche', translating: 'автомобиль' },
  { targetWord: 'tranvía', translating: 'трамвай' },
  { targetWord: 'autobús', translating: 'автобус' },
  { targetWord: 'tren', translating: 'поезд' },
  { targetWord: 'bicicleta', translating: 'велосипед' },
  { targetWord: 'tiempo', translating: 'время, погода' },
  { targetWord: 'año', translating: 'год' },
  { targetWord: 'semana', translating: 'неделя' },
  { targetWord: 'hora', translating: 'час' },
  { targetWord: 'minuto', translating: 'минута' },
  { targetWord: 'ayer', translating: 'вчера' },
  { targetWord: 'hoy', translating: 'сегодня' },
  { targetWord: 'mañana', translating: 'завтра, утро' },
  { targetWord: 'fiesta', translating: 'праздник; вечеринка' },
  { targetWord: 'vez', translating: 'раз' },
  { targetWord: 'día', translating: 'день' },
  { targetWord: 'tarde', translating: 'вечер' },
  { targetWord: 'noche', translating: 'ночь' },
  { targetWord: 'lunes', translating: 'понедельник' },
  { targetWord: 'martes', translating: 'вторник' },
  { targetWord: 'miércoles', translating: 'среда' },
  { targetWord: 'jueves', translating: 'четверг' },
  { targetWord: 'viernes', translating: 'пятница' },
  { targetWord: 'sábado', translating: 'суббота' },
  { targetWord: 'domingo', translating: 'воскресенье' },
  { targetWord: 'mes', translating: 'месяц' },
  { targetWord: 'enero', translating: 'январь' },
  { targetWord: 'febrero', translating: 'февраль' },
  { targetWord: 'marzo', translating: 'март' },
  { targetWord: 'abril', translating: 'апрель' },
  { targetWord: 'mayo', translating: 'май' },
  { targetWord: 'junio', translating: 'июнь' },
  { targetWord: 'julio', translating: 'июль' },
  { targetWord: 'agosto', translating: 'август' },
  { targetWord: 'septiembre', translating: 'сентябрь' },
  { targetWord: 'octubre', translating: 'октябрь' },
  { targetWord: 'noviembre', translating: 'ноябрь' },
  { targetWord: 'diciembre', translating: 'декабрь' },
  { targetWord: 'primavera', translating: 'весна' },
  { targetWord: 'verano', translating: 'лето' },
  { targetWord: 'otoño', translating: 'осень' },
  { targetWord: 'invierno', translating: 'зима' },
  { targetWord: 'nombre', translating: 'имя, фамилия' },
  { targetWord: 'dirección', translating: 'адрес' },
  { targetWord: 'número', translating: 'номер' },
  { targetWord: 'cumpleaños', translating: 'день рождения' },
  { targetWord: 'casado⁄a', translating: 'женатый ⁄ замужняя' },
  { targetWord: 'cosa', translating: 'вещь' },
  { targetWord: 'pluma', translating: 'ручка' },
  { targetWord: 'libro', translating: 'книга' },
  { targetWord: 'ajedrez', translating: 'шахматы' },
  { targetWord: 'teléfono', translating: 'телефон' },
  { targetWord: 'reloj', translating: 'часы' },
  { targetWord: 'peine', translating: 'расчёска' },
  { targetWord: 'televisor', translating: 'телевизор' },
  { targetWord: 'plancha', translating: 'утюг' },
  { targetWord: 'jabón', translating: 'мыло' },
  { targetWord: 'radio', translating: 'радио' },
  { targetWord: 'bolsa', translating: 'сумка' },
  { targetWord: 'mapa', translating: 'карта; открытка' },
  { targetWord: 'maleta', translating: 'чемодан' },
  { targetWord: 'regalo', translating: 'подарок' },
  { targetWord: 'cámara', translating: 'фотоаппарат; видеокамера' },
  { targetWord: 'ordenador', translating: 'компьютер' },
  { targetWord: 'película', translating: 'фильм; плёнка' },
  { targetWord: 'flor', translating: 'цветок' },
  { targetWord: 'florero', translating: 'ваза' },
  { targetWord: 'cuadro', translating: 'картина' },
  { targetWord: 'pañuelo', translating: 'носовой платок' },
  { targetWord: 'bola', translating: 'мяч' },
  { targetWord: 'globo', translating: 'воздушный шар(ик)' },
  { targetWord: 'juguete', translating: 'игрушка' },
  { targetWord: 'cuenta', translating: 'счёт' },
  { targetWord: 'sobre', translating: 'конверт' },
  { targetWord: 'papel', translating: 'бумага' },
  { targetWord: 'periódico', translating: 'газета' },
  { targetWord: 'carta', translating: 'письмо' },
  { targetWord: 'billete', translating: 'билет' },
  { targetWord: 'ropa', translating: 'одежда' },
  { targetWord: 'zapatos', translating: 'обувь' },
  { targetWord: 'abrigo', translating: 'пальто' },
  { targetWord: 'vestido', translating: 'платье' },
  { targetWord: 'camisa', translating: 'рубашка' },
  { targetWord: 'falda', translating: 'юбка' },
  { targetWord: 'guante', translating: 'перчатка' },
  { targetWord: 'sombrero', translating: 'шляпа' },
  { targetWord: 'chaqueta', translating: 'пиджак, куртка' },
  { targetWord: 'bufanda', translating: 'шарф' },
  { targetWord: 'calcetín', translating: 'носок' },
  { targetWord: 'suéter', translating: 'свитер' },
  { targetWord: 'camiseta', translating: 'футболка' },
  { targetWord: 'corbata', translating: 'галстук' },
  { targetWord: 'pantalones', translating: 'брюки' },
  { targetWord: 'mano', translating: 'рука' },
  { targetWord: 'pie', translating: 'нога' },
  { targetWord: 'cabeza', translating: 'голова' },
  { targetWord: 'ojo', translating: 'глаз' },
  { targetWord: 'lengua', translating: 'язык' },
  { targetWord: 'nariz', translating: 'нос' },
  { targetWord: 'boca', translating: 'рот' },
  { targetWord: 'oreja', translating: 'ухо' },
  { targetWord: 'qué', translating: 'что, какой' },
  { targetWord: 'cual', translating: 'какой' },
  { targetWord: 'quién', translating: 'кто' },
  { targetWord: 'dónde', translating: 'где' },
  { targetWord: 'a dónde', translating: 'куда' },
  { targetWord: 'de dónde', translating: 'откуда' },
  { targetWord: 'cómo', translating: 'как' },
  { targetWord: 'por qué', translating: 'почему' },
  { targetWord: 'cuándo', translating: 'когда' },
  { targetWord: 'yo', translating: 'я' },
  { targetWord: 'tú', translating: 'ты' },
  { targetWord: 'él', translating: 'он' },
  { targetWord: 'ella', translating: 'она' },
  { targetWord: 'usted(es)', translating: 'Вы (ед.ч.⁄мн.ч.)' },
  { targetWord: 'nosotros', translating: 'мы' },
  { targetWord: 'vosotros', translating: 'вы' },
  { targetWord: 'ellos⁄as', translating: 'они' },
  { targetWord: 'mi', translating: 'мой' },
  { targetWord: 'tu', translating: 'твой' },
  { targetWord: 'su', translating: 'его, ее, их, Ваш' },
  { targetWord: 'nuestro', translating: 'наш' },
  { targetWord: 'vuestro', translating: 'ваш' },
  { targetWord: 'de', translating: 'из; передает род. падеж' },
  { targetWord: 'a', translating: 'к' },
  { targetWord: 'sobre', translating: 'на' },
  { targetWord: 'debajo de', translating: 'под' },
  { targetWord: 'detrás de', translating: 'позади' },
  { targetWord: 'con', translating: 'с' },
  { targetWord: 'sin', translating: 'без' },
  { targetWord: 'antes de', translating: 'до, прежде' },
  { targetWord: 'después de', translating: 'после' },
  { targetWord: 'delante de', translating: 'перед' },
  { targetWord: 'entre', translating: 'между' },
  { targetWord: 'en', translating: 'в' },
  { targetWord: 'cerca de', translating: 'возле' },
  { targetWord: 'para', translating: 'для' },
  { targetWord: 'uno', translating: 'один' },
  { targetWord: 'dos', translating: 'два' },
  { targetWord: 'tres', translating: 'три' },
  { targetWord: 'cuatro', translating: 'четыре' },
  { targetWord: 'cinco', translating: 'пять' },
  { targetWord: 'seis', translating: 'шесть' },
  { targetWord: 'siete', translating: 'семь' },
  { targetWord: 'ocho', translating: 'восемь' },
  { targetWord: 'nueve', translating: 'девять' },
  { targetWord: 'diez', translating: 'десять' },
  { targetWord: 'once', translating: 'одиннадцать' },
  { targetWord: 'doce', translating: 'двенадцать' },
  { targetWord: 'trece', translating: 'тринадцать' },
  { targetWord: 'catorce', translating: 'четырнадцать' },
  { targetWord: 'quince', translating: 'пятнадцать' },
  { targetWord: 'dieciséis', translating: 'шестнадцать' },
  { targetWord: 'diecisiete', translating: 'семнадцать' },
  { targetWord: 'dieciocho', translating: 'восемнадцать' },
  { targetWord: 'diecinueve', translating: 'девятнадцать' },
  { targetWord: 'veinte', translating: 'двадцать' },
  { targetWord: 'treinta', translating: 'тридцать' },
  { targetWord: 'cuarenta', translating: 'сорок' },
  { targetWord: 'cincuenta', translating: 'пятьдесят' },
  { targetWord: 'sesenta', translating: 'шестьдесят' },
  { targetWord: 'setenta', translating: 'семьдесят' },
  { targetWord: 'ochenta', translating: 'восемьдесят' },
  { targetWord: 'noventa', translating: 'девяносто' },
  { targetWord: 'ciento', translating: 'сто' },
  { targetWord: 'mil', translating: 'тысяча' },
  { targetWord: 'viejo- старый' },
  { targetWord: 'joven', translating: 'молодой' },
  { targetWord: 'nuevo', translating: 'новый' },
  { targetWord: 'grande', translating: 'большой' },
  { targetWord: 'pequeño', translating: 'маленький' },
  { targetWord: 'hambriento', translating: 'голодный' },
  { targetWord: 'bueno', translating: 'хороший' },
  { targetWord: 'malo', translating: 'плохой' },
  { targetWord: 'bien', translating: 'хорошо' },
  { targetWord: 'mal', translating: 'плохо' },
  { targetWord: 'temprano', translating: 'ранний' },
  { targetWord: 'tarde', translating: 'поздний' },
  { targetWord: 'pasado', translating: 'последний, прошлый' },
  { targetWord: 'próximo', translating: 'следующий' },
  { targetWord: 'libre', translating: 'свободный' },
  { targetWord: 'caliente', translating: 'тёплый, горячий' },
  { targetWord: 'frío', translating: 'холодный' },
  { targetWord: 'alto', translating: 'высокий' },
  { targetWord: 'bajo', translating: 'низкий' },
  { targetWord: 'largo', translating: 'длинный, долгий' },
  { targetWord: 'corto', translating: 'короткий' },
  { targetWord: 'fácil', translating: 'лёгкий, несложный' },
  { targetWord: 'difícil', translating: 'тяжёлый, трудный' },
  { targetWord: 'ligero', translating: 'легкий (по весу)' },
  { targetWord: 'pesado', translating: 'тяжелый (по весу)' },
  { targetWord: 'oscuro', translating: 'тёмный' },
  { targetWord: 'claro', translating: 'светлый' },
  { targetWord: 'caro', translating: 'дорогой' },
  { targetWord: 'barato', translating: 'дешёвый' },
  { targetWord: 'a la izquierda', translating: 'cлева' },
  { targetWord: 'a la derecha', translating: 'справа' },
  { targetWord: 'correcto', translating: 'правильный' },
  { targetWord: 'rápido', translating: 'быстрый' },
  { targetWord: 'despacio', translating: 'медленный' },
  { targetWord: 'suave', translating: 'мягкий' },
  { targetWord: 'duro', translating: 'твёрдый' },
  { targetWord: 'bonito', translating: 'красивый' },
  { targetWord: 'atento', translating: 'внимательный' },
  { targetWord: 'triste', translating: 'печальный' },
  { targetWord: 'alegre', translating: 'радостный' },
  { targetWord: 'feliz', translating: 'счастливый' },
  { targetWord: 'listo', translating: 'готовый' },
  { targetWord: 'enojado', translating: 'сердитый' },
  { targetWord: 'principal', translating: 'основной, главный' },
  { targetWord: 'negro', translating: 'чёрный' },
  { targetWord: 'azul', translating: 'голубой; синий' },
  { targetWord: 'marrón', translating: 'коричневый' },
  { targetWord: 'verde', translating: 'зелёный' },
  { targetWord: 'gris', translating: 'серый' },
  { targetWord: 'rojo', translating: 'красный' },
  { targetWord: 'blanco', translating: 'белый' },
  { targetWord: 'amarillo', translating: 'жёлтый' },
  { targetWord: 'sí', translating: 'да' },
  { targetWord: 'no', translating: 'нет; не' },
  { targetWord: 'este', translating: 'этот' },
  { targetWord: 'ese', translating: 'тот' },
  { targetWord: 'aquel', translating: 'тот (дальше чем ese)' },
  { targetWord: 'que', translating: 'что (союз)' },
  { targetWord: 'aquí', translating: 'здесь' },
  { targetWord: 'allí', translating: 'там' },
  { targetWord: 'acá- сюда' },
  { targetWord: 'allá', translating: 'туда' },
  { targetWord: 'ahora', translating: 'сейчас, теперь' },
  { targetWord: 'ya', translating: 'уже' },
  { targetWord: 'todavía', translating: 'еще' },
  { targetWord: 'mucho⁄a⁄s', translating: 'много' },
  { targetWord: 'poco⁄a⁄s', translating: 'мало' },
  { targetWord: 'muy', translating: 'очень' },
  { targetWord: 'cada', translating: 'каждый' },
  { targetWord: 'todos', translating: 'все' },
  { targetWord: 'todo', translating: 'всё' },
  { targetWord: 'tan', translating: 'так' },
  { targetWord: 'también', translating: 'так же, тоже' },
  { targetWord: 'y', translating: 'и' },
  { targetWord: 'o', translating: 'или' },
  { targetWord: 'pero', translating: 'но' },
  { targetWord: 'porque', translating: 'потому что, так как' },
  { targetWord: 'ser', translating: 'быть, являться' },
  { targetWord: 'estar', translating: 'быть, находиться, стоять' },
  { targetWord: 'tener', translating: 'иметь' },
  { targetWord: 'poder', translating: 'мочь' },
  { targetWord: 'deber', translating: 'должен' },
  { targetWord: 'vivir', translating: 'жить' },
  { targetWord: 'permanecer', translating: 'оставаться, останавливаться' },
  { targetWord: 'venir', translating: 'приходить, приезжать' },
  { targetWord: 'ir', translating: 'идти, ехать' },
  { targetWord: 'ver', translating: 'видеть' },
  { targetWord: 'sentar', translating: 'сидеть' },
  { targetWord: 'decir', translating: 'сказать' },
  { targetWord: 'hablar', translating: 'разговаривать' },
  { targetWord: 'trabajar', translating: 'работать' },
  { targetWord: 'romper', translating: 'ломать' },
  { targetWord: 'hacer', translating: 'делать' },
  { targetWord: 'enviar', translating: 'посылать' },
  { targetWord: 'comprar', translating: 'покупать' },
  { targetWord: 'nadar', translating: 'плавать' },
  { targetWord: 'dormir', translating: 'спать' },
  { targetWord: 'despertar', translating: 'будить' },
  { targetWord: 'lavar', translating: 'мыть, cтирать' },
  { targetWord: 'probar', translating: 'пробовать' },
  { targetWord: 'encontrar', translating: 'находить' },
  { targetWord: 'traer', translating: 'приносить, привозить' },
  { targetWord: 'celebrar', translating: 'праздновать' },
  { targetWord: 'sonreír', translating: 'улыбаться' },
  { targetWord: 'llorar', translating: 'плакать' },
  { targetWord: 'costar', translating: 'стоить' },
  { targetWord: 'aprender', translating: 'учиться' },
  { targetWord: 'enseñar', translating: 'обучать' },
  { targetWord: 'escribir', translating: 'писать' },
  { targetWord: 'cambiar', translating: 'менять' },
  { targetWord: 'caer', translating: 'падать' },
  { targetWord: 'escuchar', translating: 'слушать' },
  { targetWord: 'mostrar', translating: 'показывать' },
  { targetWord: 'ganar', translating: 'побеждать' },
  { targetWord: 'pensar', translating: 'думать' },
  { targetWord: 'cerrar', translating: 'закрывать' },
  { targetWord: 'abrir', translating: 'открывать' },
  { targetWord: 'saber', translating: 'знать' },
  { targetWord: 'conocer', translating: 'быть знакомым' },
  { targetWord: 'cantar', translating: 'петь' },
  { targetWord: 'bailar', translating: 'танцевать' },
  { targetWord: 'preguntar', translating: 'спрашивать' },
  { targetWord: 'contestar', translating: 'отвечать' },
  { targetWord: 'recoger', translating: 'собирать' },
  { targetWord: 'amar', translating: 'любить' },
  { targetWord: 'dibujar', translating: 'рисовать' },
  { targetWord: 'elegir', translating: 'выбирать' },
  { targetWord: 'querer', translating: 'хотеть' },
  { targetWord: 'comer', translating: 'кушать' },
  { targetWord: 'beber', translating: 'пить' },
  { targetWord: 'dar', translating: 'давать' },
  { targetWord: 'hornear', translating: 'печь' },
  { targetWord: 'cocinar', translating: 'готовить (еду)' },
  { targetWord: 'cortar', translating: 'резать' },
  { targetWord: 'tomar', translating: 'брать' },
  { targetWord: 'esperar', translating: 'ждать' },
  { targetWord: 'leer', translating: 'читать' },
  { targetWord: 'jugar', translating: 'играть' },
  { targetWord: 'fumar', translating: 'курить' },
  { targetWord: 'crear', translating: 'создавать' },
  { targetWord: 'luchar', translating: 'бороться; драться' },
  { targetWord: 'gracias', translating: 'спасибо' },
  { targetWord: 'perdón', translating: 'извини(те)' },
  { targetWord: 'por favor', translating: 'пожалуйста (прошу)' },
  { targetWord: 'de nada', translating: 'пожалуйста, не за что' },
  { targetWord: 'qué lástima', translating: 'жаль' },
  { targetWord: 'hasta la vista', translating: 'до свидания' },
  { targetWord: 'canción', translating: 'песня' },
  { targetWord: 'música', translating: 'музыка' },
  { targetWord: 'tamaño', translating: 'размер' },
  { targetWord: 'dinero', translating: 'деньги' },
  { targetWord: 'felicidad', translating: 'счастье' },
  { targetWord: 'suerte', translating: 'удача' },
  { targetWord: 'broma', translating: 'шутка' },
  { targetWord: 'sorpresa', translating: 'сюрприз' },
  { targetWord: 'problema', translating: 'проблема' },
  { targetWord: 'lluvia', translating: 'дождь' },
  { targetWord: 'viento', translating: 'ветер' },
  { targetWord: 'nieve', translating: 'снег' },
  { targetWord: 'cielo', translating: 'небо	' }
];
